# Generated by Django 3.2.20 on 2023-07-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_key', models.PositiveIntegerField(default=0, verbose_name='')),
                ('show', models.BooleanField(default=True, verbose_name='Отображать')),
                ('top_subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='подзаголовок сверху')),
                ('title', models.CharField(max_length=255, verbose_name='основной заголовок')),
                ('bottom_subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='подзаголовок снизу')),
            ],
            options={
                'verbose_name': 'преимущество',
                'verbose_name_plural': 'преимущества',
                'ordering': ['order_key'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_key', models.PositiveIntegerField(default=0, verbose_name='')),
                ('show', models.BooleanField(default=True, verbose_name='Отображать')),
                ('name', models.CharField(max_length=255, verbose_name='Название пункта')),
                ('url', models.CharField(max_length=255, verbose_name='url')),
            ],
            options={
                'verbose_name': 'пункт меню',
                'verbose_name_plural': 'пункты меню',
                'ordering': ['order_key'],
            },
        ),
    ]
